import { Inter as interFont } from 'next/font/google';
import Head from 'next/head';
import TaskList from '@/components/TaskList';

const inter = interFont({ subsets: ['latin'] });

const Home = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <div>
          <TaskList />
        </div>
      </main>
    </>
  );
};
export default Home;
