import { Inter } from 'next/font/google'
import Head from 'next/head'
import TaskList from '@/pages/components/TaskList'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const Home = () =>{
    return (
        <>
        <Head>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
        <div>
        <TaskList />
        </div>
        </main>       
        </>        
    )
}
export default Home;
