import { Inter } from 'next/font/google';
import Head from 'next/head';
import ClickCounter from 'src/pages/components/ClickCounter';

// eslint-disable-next-line new-cap
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${inter.className}`}>
        <div>
          <ClickCounter />
          <ClickCounter />
        </div>
      </main>
    </>
  );
}
